name: Playwright e2e Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      EMAIL: ${{ secrets.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}
      BROWSER: ${{ secrets.BROWSER }}
      HEADLESS: ${{ secrets.HEADLESS }}
      TIMEOUT: ${{ secrets.TIMEOUT }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Dependencies
        run: npm ci

      - name: Install Playwright Browsers
        #run: npx playwright install --with-deps
        run: npx playwright install --with-deps chromium

      - name: Run Playwright Tests (Headless)
        #run: npx playwright test  --reporter=html,list
        run: npx playwright test --project=chromium --reporter=html,list

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/

      - name: Upload Traces & Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: test-results/
